# fly.toml app configuration file generated for self-hosted-ai-starter-kit-n8n on 2025-06-26T04:10:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'self-hosted-ai-starter-kit-n8n'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
